-- Legacy Music Center — Push notification event deduplication
create table if not exists public.push_delivery_events (
  id bigint generated by default as identity primary key,
  event_key text not null,
  user_type text not null,
  user_id text not null,
  created_at timestamptz not null default now(),
  constraint push_delivery_events_unique unique (event_key, user_type, user_id)
);

create index if not exists push_delivery_events_created_idx
  on public.push_delivery_events (created_at desc);

alter table public.push_delivery_events enable row level security;

comment on table public.push_delivery_events is
  'Server-side dedupe log for scheduled Web Push notifications such as class reminders.';
